Repository leroy-merlin-br/bazaarvoice-feed, pull requests merged in 2018-07, with the labels that each got.

#1 Clean up code and upgrade to php 7.2
  README.md
  composer.json
  src/Elements/BrandElement.php
  src/Elements/BrandElementInterface.php
  src/Elements/CategoryElement.php
  src/Elements/CategoryElementInterface.php
  src/Elements/ElementBase.php
  src/Elements/ElementInterface.php
  src/Elements/FeedElement.php
  src/Elements/FeedElementInterface.php
  src/Elements/ProductElement.php
  src/Elements/ProductElementInterface.php
  src/ProductFeed.php
  src/ProductFeedInterface.php
  tests/ProductFeedTest.php
Labels: code-review

#4 Add more test cases for package
  .gitignore
  composer.json
  phpunit.xml
  src/Elements/ProductElementInterface.php
  tests/ProductFeedTest.php
  tests/Unit/Elements/BrandElementTest.php
  tests/Unit/Elements/CategoryElementTest.php
Labels: work-in-progress

#7 Adds TravisCI and Coveralls
  .coveralls.yml
  .travis.yml
  Makefile
  README.md
  composer.json
  phpunit.xml.dist
  src/Elements/FeedElement.php
  tests/Unit/ProductFeedTest.php
Labels: code-review, enhancement

#8 Order Feed
  composer.json
  phpunit.xml
  src/AbstractFeed.php
  src/Elements/ElementBase.php
  src/Elements/ElementInterface.php
  src/Elements/FeedElement.php
  src/Elements/InteractionElement.php
  src/Elements/ProductElement.php
  src/FeedInterface.php
  src/Order/Feed.php
  src/Product/Feed.php
  src/ProductFeedInterface.php
  tests/Feature/FeedTest.php
  tests/Unit/Elements/BrandElementTest.php
  tests/Unit/Elements/CategoryElementTest.php
  tests/Unit/Elements/ElementBaseTest.php
  tests/Unit/Elements/ProductElementTest.php
  tests/Unit/Order/FeedTest.php
  tests/Unit/Product/FeedTest.php
  tests/fixtures/brand-feed.xml
  tests/fixtures/category-feed.xml
  tests/fixtures/interaction-feed.xml
  tests/fixtures/product-feed.xml
Labels: work-in-progress

#10 Standartize package
  src/Elements/FeedElementInterface.php
  tests/Unit/Product/FeedTest.php
Labels: code-review

#13 fix readme
  README.md
Labels: code-review

#14 Fix references in badges
  README.md
Labels: code-review

#15 Adjust ProductElementInterface
  src/Elements/ProductElementInterface.php
Labels: code-review

#17 Interaction improvements
  src/AbstractFeed.php
  src/Elements/FeedElement.php
  src/Elements/FeedElementInterface.php
  src/Elements/Interaction/FeedElement.php
  src/Elements/Interaction/InteractionElement.php
  src/Elements/Interaction/ProductElement.php
  src/FeedInterface.php
  src/Interaction/Feed.php
  tests/Feature/FeedTest.php
  tests/Unit/Elements/Interaction/FeedElementTest.php
  tests/Unit/Interaction/FeedTest.php
  tests/fixtures/interaction-feed.xml
Labels: code-review

#18 throws exceptions when cannot generate xml files
  src/AbstractFeed.php
Labels: code-review

#19 Without Compression Option
  src/AbstractFeed.php
  tests/Unit/Product/FeedTest.php
Labels: code-review
